_wandb:
    value:
        cli_version: 0.26.1
        e:
            xteryzdnccepqjvkrgjvb1wtn2ow1moi:
                args:
                    - --method
                    - paragraph
                codePath: scripts/run_ingest.py
                codePathLocal: scripts/run_ingest.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "137369751552"
                        used: "78013165568"
                email: ngangada@asu.edu
                executable: /home/ngangada/.venv/bin/python
                git:
                    commit: b464dbcca936e78cc9c3161f6993a8c85b259f1a
                    remote: https://narottaman:@github.com/narottaman/rag-document-assistant.git
                host: sol-login02
                memory:
                    total: "33149075456"
                os: Linux-4.18.0-553.77.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /scratch/ngangada/portfolio/rag-document-assistant/scripts/run_ingest.py
                python: CPython 3.10.18
                root: /scratch/ngangada/portfolio/rag-document-assistant
                startedAt: "2026-05-01T01:30:17.366579Z"
                writerId: xteryzdnccepqjvkrgjvb1wtn2ow1moi
        m: []
        python_version: 3.10.18
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.26.1
            "8":
                - 2
            "10":
                - 20
            "12": 0.26.1
            "13": linux-x86_64
chunk_method:
    value: paragraph
chunk_overlap:
    value: 50
chunk_size:
    value: 512
pdf_dir:
    value: data/raw/pdfs
